### ISSUE TITLE
Sideways tables suggestion

### ISSUE THREAD

**Issue by zoqaeski** [carbeck/ayerigrammar#1]
You might find the [`pdflscape`](http://www.ctan.org/pkg/pdflscape) package useful, as it allows you to rotate the pages in the PDF on-screen whilst still printing normally. I use it in my grammar so the rotated tables aren't as jarring to the eye: it's difficult to rotate a page in a PDF viewer, but easy to rotate a printed work.

**Comment by carbeck** [comment]
Thanks for the suggestion, I'll look into it! I had actually wondered myself because yeah, when you're reading this on screen, tilting your head is certainly not a solution ;)

**Comment by carbeck** [comment]
Unfortunately, `pdflscape` seems to issue `\clearpage` before and after the `landscape` environment instead of reflowing text around a float :disappointed: I suppose, this issue will stay open after all.

**Comment by carbeck** [comment]
Unfortunately, `pdflscape` seems to issue `\clearpage` before and after the `landscape` environment. Unlike in `sidewaystable` from `rotating`, text will thus not flow around a `landscape` :disappointed: I suppose, this issue will stay open for the time being.

**Comment by carbeck** [comment]
I found that I can use the `\afterpage` command from the `afterpage` package to do the floating right. Thanks again for the suggestion, however!
